plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-hacker
title: [Software Engineering 2 - Journal]
description: ["This is my journal for COMP-3613: Software Engineering II semester long Group project"]
